classdef LightfieldDatasets < setup.enums.datasets.TemplateDatasets
    %LIGHTFIELDDATASETS
    %   Package to download lightfield dataset files.
    
    properties (SetAccess = immutable)
        format      % Lightfield format in dataset
    end
   
    methods
        function self = LightfieldDatasets(url,zipFilepath,folderPath,format)
            %
            % Lightfield datasets instance.
            %
            self@setup.enums.datasets.TemplateDatasets(url,zipFilepath,folderPath);

            % Define format for lightfield structure
            self.format = format;
        end
    end
    
    enumeration
        LFTOOLBOX_SAMPLES ( 'http://www-personal.acfr.usyd.edu.au/ddan1654/LFToolbox0.5_Samples.zip' ...
                          , 'LFToolbox0.5_Samples.zip' ...
                          , ['dansereau' filesep] ...
                          , lightfield.enums.Formats.DANSEREAU_FORMAT() )
        CALIBRATION_DATASET_CVPR2013_A( 'http://www-personal.acfr.usyd.edu.au/ddan1654/PlenCalCVPR2013DatasetA.zip' ...
                                      , 'PlenCalCVPR2013DatasetA.zip' ...
                                      , ['dansereau' filesep 'Cameras' filesep 'A000424242' filesep 'PlenCalCVPR2013DatasetA'] ...
                                      , lightfield.enums.Formats.DANSEREAU_FORMAT() )
        CALIBRATION_DATASET_CVPR2013_B( 'http://www-personal.acfr.usyd.edu.au/ddan1654/PlenCalCVPR2013DatasetB.zip' ...
                                      , 'PlenCalCVPR2013DatasetB.zip' ...
                                      , ['dansereau' filesep 'Cameras' filesep 'A000424242' filesep 'PlenCalCVPR2013DatasetB'] ...
                                      , lightfield.enums.Formats.DANSEREAU_FORMAT() )
        CALIBRATION_DATASET_CVPR2013_C( 'http://www-personal.acfr.usyd.edu.au/ddan1654/PlenCalCVPR2013DatasetC.zip' ...
                                      , 'PlenCalCVPR2013DatasetC.zip' ...
                                      , ['dansereau' filesep 'Cameras' filesep 'A000424242' filesep 'PlenCalCVPR2013DatasetC'] ...
                                      , lightfield.enums.Formats.DANSEREAU_FORMAT() )
        CALIBRATION_DATASET_CVPR2013_D( 'http://www-personal.acfr.usyd.edu.au/ddan1654/PlenCalCVPR2013DatasetD.zip' ...
                                      , 'PlenCalCVPR2013DatasetD.zip' ...
                                      , ['dansereau' filesep 'Cameras' filesep 'A000424242' filesep 'PlenCalCVPR2013DatasetD'] ...
                                      , lightfield.enums.Formats.DANSEREAU_FORMAT() )
        CALIBRATION_DATASET_CVPR2013_E( 'http://www-personal.acfr.usyd.edu.au/ddan1654/PlenCalCVPR2013DatasetE.zip' ...
                                      , 'PlenCalCVPR2013DatasetE.zip' ...
                                      , ['dansereau' filesep 'Cameras' filesep 'A000424242' filesep 'PlenCalCVPR2013DatasetE'] ...
                                      , lightfield.enums.Formats.DANSEREAU_FORMAT() )
    end
end